# Generated by Django 2.2.6 on 2020-01-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_person_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='zip_code',
        ),
    ]
